# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotluck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Hotel',
        ),
    ]
